name: firebase
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.3
  form_field_validator: ^1.1.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.1
  diacritic: ^0.1.3
  cloud_firestore: ^5.6.0
  firebase_database: ^11.2.0
  intl: ^0.19.0
  sqflite: ^2.4.1
  path_provider: ^2.0.11
  provider: ^6.1.2
  http: ^0.13.0
  flutter_bloc: ^8.1.6
  google_fonts: ^4.0.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  animate_do: ^3.3.4
  glassmorphism: ^3.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_webservice: ^0.0.20-nullsafety.1
  webview_flutter: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  animated_text_kit: ^4.2.1
  local_auth: ^2.1.6
  simple_animations: ^5.0.0+3
  font_awesome_flutter: ^10.0.0
  flutter_secure_storage: ^9.2.3
  flutter_facebook_auth: ^6.0.0
  bloc: ^8.1.4
  googleapis: ^13.1.0
  googleapis_auth: ^1.3.0
  url_launcher: ^6.0.10
  video_player: ^2.9.2
  chewie: ^1.7.1
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Illustrations/
    - assets/icons/
    - assets/images/faceDung.jpg

